### ISSUE TITLE
add tidyverse and reshape2 to depdencies

### ISSUE THREAD

**Issue by HedvigS** [grambank/rgrambank#11]
I think tidyverse and reshape2 should be installed and loaded for rgrambank.

**Comment by SimonGreenhill** [comment]
I'd rather add dependencies explicitly as needed (e.g. dplyr vs. all of tidyverse).

**Comment by HedvigS** [comment]
Okay. Once the current PRs are merged in, I can go check exactly which packages are used where.

**Comment by HedvigS** [comment]
so far I see that dplyr, readr, tidyr and reshape2 specifically would be good. Unless you want to re-write some things.

**Comment by SimonGreenhill** [comment]
I think most of these are now in the dependencies (i.e. tests won't work unless they're there)
