### ISSUE TITLE
add random seed argument to language_level_DF

### ISSUE THREAD

**Issue by HedvigS** [grambank/rgrambank#24]
add "random_seed = NULL" to arguments

```
    #There is a random element in the duplicate dropping. If you want it to give the same result everytime, set a random seed.
if(is.numeric(random_seed)){
    set.seed(random_seed)
}
```

**Comment by SimonGreenhill** [comment]
Users can just use `set.seed()` before calling the function - adding this to the function means we need to document and maintain more code, and our function messes with the global environment scope (.Random.seed)
