### ISSUE TITLE
add get_languages_for_clade function

### ISSUE THREAD

**Issue by SimonGreenhill** [grambank/rgrambank#27]
see: 
https://twitter.com/SimonJGreenhill/status/1711127649131925681

**Comment by SimonGreenhill** [comment]
Added in ccfa72f550300275ef1c43e9943cc91d645be638

**Comment by HedvigS** [comment]
Huh, okay. This seems to me a bit of an unnecessary function, but okay.
Should it say somewhere that this only relates to glottolog trees?
