### ISSUE TITLE
new function: make theo scores

### ISSUE THREAD

**Issue by HedvigS** [grambank/rgrambank#5]
Adaptation of these two scripts:

- https://github.com/grambank/grambank-analysed/blob/main/R_grambank/make_theo_score_fusion.R
- https://github.com/grambank/grambank-analysed/blob/main/R_grambank/make_theo_scores.R

To calculate the theoretical scores (fusion, informativity etc).

**Comment by SimonGreenhill** [comment]
Question: do these have any use outside the previous paper? this type of function tends to get stale very quickly as it  has limited reusability for other people.

**Comment by HedvigS** [comment]
It has a use outside of the release paper, in the paper on social effects on complexity. It would have been good to have this function in the process of writing the code there.

I do not currently know other papers that need this, but it's a popular part of the release paper and I think it would be practical to be able to easily derive the counts for new versions of Grambank.

**Comment by HedvigS** [comment]
Angela told me yesterday that she would benefit from this function in the disparity project. So, that's at least one future paper using it besides me and Olena for already submitted things.
