### ISSUE TITLE
new function: grabbing data from zenodo

### ISSUE THREAD

**Issue by HedvigS** [grambank/rgrambank#7]
I think it'd be useful to implement this function:

- https://github.com/HedvigS/Oceanic_computational_ASR/blob/main/code/fun_def_get_zenodo.R

example of use here:

- https://github.com/HedvigS/Oceanic_computational_ASR/blob/main/code/02_get_zenodo_dirs.R

**Comment by HedvigS** [comment]
Or this could be over in rcldf: https://github.com/SimonGreenhill/rcldf/pull/30

**Comment by SimonGreenhill** [comment]
this is now in rcldf for downloading cldf releases -- but why did you want to download a bunch of old grambank analyses?

**Comment by HedvigS** [comment]
> this is now in rcldf for downloading cldf releases -

Great :)! 

> - but why did you want to download a bunch of old grambank analyses?
 
I don't understand the question. Colleagues who are working with grambank data often need to fetch data and are fetching it in non-optimal ways with moving derived files around. Explicitly fetching a particular version of cldf data from the internet seems smart and explicit to me. Then the code says exactly what version and the workflow is clear from data input to analysis and plotting etc.
