### ISSUE TITLE
languoids table fetching/appending

### ISSUE THREAD

**Issue by HedvigS** [grambank/rgrambank#8]
When I asked Angela, Eze etc about functions they'd like to see in rgrambank, Olena said: 

`I often need to grab Latitude, Longitude, Macroarea, Family_ID and similar columns from glottolog. Since the glottolog file is used for many of those tasks you describe (and we would ideally rely on the same glottolog version), maybe there could be an easy way to add some glottolog column directly.`

grambank-cldf contains a language table that contains this data for grambank languoids. Sometimes the language-level parent data may not be there, and if it is necessary to compare to other datasets it may be that a combination of the language and values tables of glottolog-cldf may be necessary.

To answer this suggestion, we could:

a) provide more documentation on how to read in and add the grambank-cldf language table
b) provide a function that makes a language-levelled language table (maybe with things from glottolog-cldf)
c) point people to #7 and show how to use that approach to fetch language data from glottolog (merging language and value tables, for example like [this](https://github.com/grambank/grambank-analysed/blob/main/R_grambank/make_glottolog-cldf_table.R)

**Comment by HedvigS** [comment]
With the download option in rcldf, we can work this into a README and see if this satisfies Olena.

**Comment by SimonGreenhill** [comment]
How about just this?

```{r}
grambank <- load_grambank()
glottolog <- load_grambank()

languages <- grambank$tables$LanguageTable %>%
    left_join(glottolog$tables$LanguageTable)
```

Now added to README.md

**Comment by HedvigS** [comment]
That looks good to me! I'll test run it on Olena.
